// <auto-generated />
using System;
using LawOfficeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawOfficeManagement.Migrations
{
    [DbContext(typeof(LawOfficeContext))]
    [Migration("20251223090706_RenameDocumentCaseToCaseFile")]
    partial class RenameDocumentCaseToCaseFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LawOfficeManagement.Models.CaseFile", b =>
                {
                    b.Property<int>("CaseFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseFileId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseFileId");

                    b.HasIndex("ClientId");

                    b.ToTable("CaseFiles");
                });

            modelBuilder.Entity("LawOfficeManagement.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LawOfficeManagement.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("CaseFileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("CaseFileId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("LawOfficeManagement.Models.WorkLog", b =>
                {
                    b.Property<int>("WorkLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkLogId"));

                    b.Property<int>("CaseFileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkLogId");

                    b.HasIndex("CaseFileId");

                    b.ToTable("WorkLogs");
                });

            modelBuilder.Entity("LawOfficeManagement.Models.CaseFile", b =>
                {
                    b.HasOne("LawOfficeManagement.Models.Client", "Client")
                        .WithMany("CaseFiles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LawOfficeManagement.Models.Document", b =>
                {
                    b.HasOne("LawOfficeManagement.Models.CaseFile", "CaseFile")
                        .WithMany("Documents")
                        .HasForeignKey("CaseFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseFile");
                });

            modelBuilder.Entity("LawOfficeManagement.Models.WorkLog", b =>
                {
                    b.HasOne("LawOfficeManagement.Models.CaseFile", "CaseFile")
                        .WithMany("WorkLogs")
                        .HasForeignKey("CaseFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseFile");
                });

            modelBuilder.Entity("LawOfficeManagement.Models.CaseFile", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("LawOfficeManagement.Models.Client", b =>
                {
                    b.Navigation("CaseFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
